// --- START OF FILE forbidden-names.js ---

const forbiddenNames = [
    // --- Rôles et Système (pour éviter l'usurpation d'identité) ---
    "admin", "administrator", "administrateur",
    "aide", "bot", "dev", "developer", "developpeur", "dummy", "game", "gamemaster",
    "gmaster", "gacha", "guest", "help", "maitre", "maître", "mj", "mod", "moderateur",
    "moderator", "owner", "proprietaire", "root", "serveur", "server", "staff",
    "support", "sys", "system", "systeme", "test", "ultime", "user", "utilisateur",

    // --- Insultes et Vulgarités (Français) ---
    "abruti", "abrutie", "andouille", "arsouille", "baise", "baiser", "balourd",
    "batard", "batarde", "benêt", "blaireau", "boloss", "boudin",
    "bouffon", "bougre", "bourrique", "bouse", "bouseux", "branleur", "branleuse",
    "branquignole", "burne", "bécasse", "cageot", "casse-couilles", "charlatan", "chenapan",
    "chier", "chieur", "chieuse", "cinglé", "cloche", "clown", "cochon", "cocu",
    "con", "concombre", "connard", "connasse", "conne", "corniaud", "cornichon",
    "couille", "couillon", "courge", "crado", "crapule", "crassux", "crétin",
    "cruche", "cuistre", "cul", "cynique", "dinde", "ducon", "dufion", "débile",
    "dégueu", "dégueulasse", "dégénéré", "dépravé", "empaffé", "emmerde",
    "emmerder", "emmerdeur", "emmerdeuse", "encule", "enculer", "enculeur",
    "enfoiré", "face de rat", "faquin", "faux-cul", "fdp", "fiente", "filou",
    "filsdepute", "finaud", "fion", "flaque", "foille", "foutre", "foutriquet",
    "frappe", "fripouille", "fruste", "fumier", "garce", "glandu", "gnangnan",
    "gogo", "gouffre", "gougnafier", "goujat", "gouine", "gourde", "gourgandine", "gueule",
    "gueux", "guignol", "grognasse", "gros-jean", "greluche", "goinfre",
    "hypocrite", "idiot", "ignare", "imbécile", "imposteur", "incapable", "incruster",
    "ivrogne", "jacasse", "jean-foutre", "jobard", "kévin", "laideron", "larve",
    "licheur", "lope", "lopette", "loufiat", "lourdaud", "lèche-bottes", "lèche-cul",
    "mal-baisé", "malfrat", "malotru", "manant", "mange-merde", "maquereau",
    "menteur", "merde", "merdeux", "mielleux", "migraine", "minable", "minus",
    "miteux", "m'n'fils", "monstre", "morpion", "morveux", "mou-du-genou",
    "moule", "mouton", "mufle", "nage-vite", "nanar", "naze", "niais", "niaiseux",
    "nigaud", "nique", "niquer", "nouille", "nul", "négligé", "oie", "oisif",
    "ordure", "osti", "pacotille", "pailote", "paltoquet", "pantouflard",
    "papelard", "parasite", "parvenu", "passéiste", "patapouf", "patate",
    "pataud", "pauvre con", "pauvre type", "paysan", "pd", "pede", "pédé",
    "peigne-cul", "pervers", "pimbêche", "pingre", "pisse-froid",
    "pisse-vinaigre", "pisseux", "pisseuse", "pleutre", "plouc", "pochetrot",
    "poivrot", "polisson", "poltron", "pompe-à-merde", "porc", "pot-de-vin",
    "poubelle", "poule mouillée", "pouffiasse", "pouilleux", "pourri",
    "pourriture", "profiteur", "prolétaire", "prostituée", "prout", "provincial",
    "puant", "pucelle", "punaise", "purin", "pus", "putain", "pute", "péquenot",
    "pétasse", "pète-sec", "pénible", "quadragénaire", "quenelle", "quiche",
    "raclure", "ramassis", "rampant", "rapace", "rase-mottes", "raté", "rebut",
    "relou", "renégat", "reste", "ridicule", "rieur", "robinet", "roquet",
    "roublard", "rustre", "rêveur", "résidu", "saboteur", "sac à merde",
    "sac à vin", "sacripant", "sadique", "sagouin", "salaud", "sale", "saligaud",
    "salopard", "salope", "saltimbanque", "sans-dents", "saperlipopette",
    "schlingue", "schnock", "scorta", "serf", "serpillère", "simplet", "singe",
    "sinistre", "snob", "sombre", "sot", "souillon", "soumis", "sous-merde",
    "spartiate", "stupide", "suceur", "suint", "sévice", "sélénite", "tafiole",
    "tante", "tapette", "taré", "tarlouze", "tartuffe", "tg", "thon", "tocard",
    "tordu", "traînée", "tringlot", "triple buse", "trou-du-cul", "trouduc",
    "tâcheron", "tête de nœud", "va-nu-pieds", "vaurien", "vautour", "vermine",
    "veuve-poignet", "vieux schnock", "vioque", "zob",

    // --- Insultes et Vulgarités (Anglais) ---
    "arse", "asehole", "ass", "asshole", "bastard", "bitch", "bollocks", "bugger",
    "cock", "cocksucker", "crap", "cunt", "damn", "dick", "douche", "fuck",
    "fucker", "fucking", "goddamn", "hell", "jerk", "jizz", "mf", "motherfucker",
    "piss", "prick", "pussy", "shag", "shit", "slut", "tits", "twat", "wank",
    "wanker", "whore",

    // --- Insultes et Vulgarités (Autres Langues) ---
    "arschloch", "cabron", "cazzo", "fotze", "hurensohn", "joder", "maricon",
    "merda", "mierda", "pendejo", "puta", "puto", "puttana", "scheisse",
    "stronzo", "vaffanculo", "wichser",

    // --- Propos Haineux et Discriminatoires ---
    "alqaeda", "apartheid", "arabe", "ariviste", "aryen", "asiatique", "auschwitz", "autiste",
    "bamboula", "baraki", "basané", "beaner", "beurette", "bicot", "blanc", "blanche",
    "boche", "bougnoul", "boukak", "catho", "chicano", "chinetoque", "chink", "chleuh",
    "chrétien", "circoncis", "coloré", "colonialiste", "communiste", "confédéré",
    "coolie", "cosaque", "croisé", "crouille", "créole", "daesh", "dago",
    "dhimmi", "djellaba", "dominant", "doriforo", "doryphore", "esclave",
    "eskimo", "ethnique", "eugénisme", "européen", "extrémiste", "facho",
    "fag", "faggot", "fanatique", "farang", "fasciste", "fatma", "femmelette",
    "fenek", "feuj", "flamench", "folle", "forain", "franco", "franquiste",
    "fritz", "frondeur", "frontiste", "féministe", "gadjé", "gai", "gaouar", "gaouri",
    "ghetto", "gitan", "godon", "gogol", "gook", "goudou", "goy", "gringo",
    "gros", "grosse", "grosse vache", "gwer", "gypsy", "harki", "heeb", "heil",
    "hermaphrodite", "hindou", "hitler", "holocauste", "homophobe", "homosexuel",
    "hongrois", "huguenot", "hun", "hétéro", "illettré", "impur", "indigène",
    "infidèle", "intégriste", "invalide", "isis", "islamiste", "israélite",
    "jaune", "jihad", "jihâd", "juif", "judéo-nazi", "kafir", "kahlouch",
    "keffieh", "kike", "kkk", "ku klux klan", "ladin", "lapon", "lapin",
    "latino", "lesbienne", "libanais", "lusitanien", "macaroni", "maghrébin",
    "mahr", "mahometan", "manouche", "maquettiste", "marrane", "marxiste",
    "maure", "mauricien", "mestic", "metis", "mexicain", "misandre", "misogyne",
    "moha", "mongol", "mongolien", "moricaud", "moudjahid", "mulâtre",
    "musulman", "mussolini", "mâle", "mégro", "mélanoderme", "ménagère",
    "métèque", "nabatéen", "nationaliste", "nazi", "nazy", "negre", "negresse",
    "negro", "négrier", "niak", "niakoué", "nigger", "nigga", "niqab", "noir",
    "occidental", "oriental", "orthodoxe", "otaku", "ottoman", "païen",
    "paki", "palefrenier", "palestinien", "papiste", "paria", "patriarcat",
    "persan", "phalangiste", "philippin", "pied-noir", "pinoy", "polack",
    "polak", "polonais", "polognard", "protestant", "puritain", "pygmé",
    "quaker", "queer", "rabouin", "racaille", "racist", "raciste", "radical",
    "rasta", "ratichon", "raton", "rebelle", "renoi", "retard", "rital", "romani",
    "romanichel", "rosbif", "roumain", "russe", "russcof", "réactionnaire",
    "réfugié", "salafiste", "sarrasin", "sataniste", "sauvage", "schismatic",
    "schizo", "serbe", "serron", "sexist", "sexiste", "shemale", "shiite",
    "shoah", "siegheil", "sikh", "sioniste", "skinhead", "slave", "socialiste",
    "soumission", "spic", "ss", "stalinien", "sunnite", "suprémaciste", "syrien",
    "ségrégation", "sémite", "taliban", "talmud", "tatar", "terroriste",
    "teuton", "tiers-mondiste", "toubab", "tourangeau", "traditionnaliste",
    "trans", "transphobe", "tranny", "trav", "triso", "turc", "tyran",
    "tchécoslovaque", "tzigane", "ukrainien", "ultra", "valaque", "vandale",
    "vassal", "vaudou", "vénitien", "vietnamien", "viking", "wetback",
    "whitepower", "whitesupremacy", "wog", "wop", "yankee", "yid", "youpin",
    "zoulou", "ébène",

    // --- Références à la drogue et à l'alcool ---
    "alcool", "beuh", "biere", "cannabis", "cocaine", "coke", "crack", "drogue",
    "drug", "ecstasy", "heroin", "heroine", "joint", "lsd", "marijuana", "meth",
    "opium", "pope", "pot", "speed", "vin", "vodka", "weed", "whisky",

    // --- Violence, Gore et Sujets Sensibles ---
    "anorexia", "anorexique", "assassin", "blood", "bomb", "bombe", "bulimia",
    "boulimie", "cutting", "gore", "kill", "meurtre", "murder", "rape", "sang",
    "selfharm", "suicidal", "suicide", "torture", "tuer", "viol", "violer",

    // --- Thèmes sexuels explicites ---
    "anal", "anus", "boobs", "clitoris", "dildo", "erection", "gangbang",
    "hentai", "incest", "inceste", "masturbate", "masturber", "milf", "orgasm",
    "orgasme", "penis", "porn", "porno", "pénis", "sexe", "sex", "sperm",
    "sperme", "vagin", "vagina", "xxx", "yiff", "érection",

    // --- Variations et Leet Speak (pour la méthode .includes()) ---
    "@ss", "a$$", "a55", "b!tch", "b1tch", "c*ck", "c*n", "c*nnard", "c*nnasse",
    "c0ck", "enc*lé de", "f*ck", "f*cker", "f*cking", "f4g", "fu*k", "fuk",
    "p*ssy", "p0rn", "phuck", "phuk", "pr0n", "s3x", "sh1t", "tit5", "wh0re"
];
// --- END OF FILE forbidden-names.js ---